Repository skni-kod/SKNIBot, pull requests merged in 2021-08, with the labels that each got.

#65 Update EightBallCommand.cs
  SKNIBot/Core/Commands/TextCommands/EightBallCommand.cs
Labels: refactoring

#66 Fix autoresponses
  SKNIBot/Core/Bot.cs
  SKNIBot/Core/MessageResponds/EmotionalTitanicFluteRespond.cs
  SKNIBot/Core/MessageResponds/SomeoneCalledMessageRespond.cs
  SKNIBot/Core/MessageResponds/WhatIsLoveRespond.cs
  SKNIBot/Core/MessageResponds/XDMessageRespond.cs
Labels: enhancement

#67 Feature/post long message separator
  SKNIBot/Core/Commands/ModerationCommands/RoleCommand.cs
  SKNIBot/Core/Commands/TextCommands/EightBallCommand.cs
  SKNIBot/Core/Helpers/PostLongMessageHelper.cs
Labels: enhancement

#69 Develop
  SKNIBot/Core/Bot.cs
  SKNIBot/Core/Commands/ModerationCommands/RoleCommand.cs
  SKNIBot/Core/Commands/TextCommands/EightBallCommand.cs
  SKNIBot/Core/Commands/TextCommands/JokeCommand.cs
  SKNIBot/Core/Database/Models/StaticDB/SimpleResponse.cs
  SKNIBot/Core/Helpers/PostLongMessageHelper.cs
  SKNIBot/Core/MessageResponds/EmotionalTitanicFluteRespond.cs
  SKNIBot/Core/MessageResponds/SomeoneCalledMessageRespond.cs
  SKNIBot/Core/MessageResponds/WhatIsLoveRespond.cs
  SKNIBot/Core/MessageResponds/XDMessageRespond.cs
  SKNIBot/Core/Services/SimpleResponseService/SimpleResponseResponse.cs
  SKNIBot/Core/Services/SimpleResponseService/SimpleResponseService.cs
  SKNIBot/StaticDatabase.sqlite
Labels: bug, enhancement, refactoring

#70 Moved simple message responses to database
  SKNIBot/Core/Bot.cs
  SKNIBot/Core/Database/Models/StaticDB/MessageResponse.cs
  SKNIBot/Core/Database/StaticDBContext.cs
  SKNIBot/Core/MessageResponds/SomeoneCalledMessageRespond.cs
  SKNIBot/Core/MessageResponds/WhatIsLoveRespond.cs
  SKNIBot/Core/MessageResponds/XDMessageRespond.cs
  SKNIBot/Core/Services/MessageResponseService/MessageResponseService.cs
  SKNIBot/StaticDatabase.sqlite
Labels: enhancement
